### ISSUE TITLE
Please add <supports-screens> to the manifest

### ISSUE THREAD

**Issue by girst** [atd/HandyNotes#14]
Hi, this app would be perfect for me if the UI wasn't scaled so badly. This should be an easy fix though. 

```diff
diff --git a/AndroidManifest.xml b/AndroidManifest.xml
index b02fb9a..701cfd0 100644
--- a/AndroidManifest.xml
+++ b/AndroidManifest.xml
@@ -85,5 +85,6 @@
                </receiver>
     </application>
     <uses-sdk android:minSdkVersion="4" android:targetSdkVersion="4" />
+    <supports-screens android:xlargeScreens="true" />
 
 </manifest> 
```

(please also add a new tag, so f-droid picks it up)

**Comment by atd** [comment]
Done and bumped to v1.3

Please let me know if it worked

**Comment by girst** [comment]
There's a problem. I'm relaying some information from the f-droid folks[1]:

> We can't because the author didn't update the version code. Also I
> have no idea why
> [1.5](https://github.com/atd/HandyNotes/blob/2aab68d58acaf819db4e76760a13d582fc1ee38f/AndroidManifest.xml#L5)
> is tagged as 1.3.

[1]: https://gitlab.com/fdroid/fdroiddata/issues/1357#note_100024324

**Comment by atd** [comment]
Sorry for the mess @girst , old code...

I bumped v1.6 and tagged it
