### ISSUE TITLE
Giant CPU usage of Handynotes in RAID for some reason.

### ISSUE THREAD

**Issue by Evonos** [atd/HandyNotes#21]
Hi there as i earlier in shadowlands reported sucessfully CPU bugs which got later fixed by the addon devs .

id like to report new ones in dragonflight.
https://i.imgur.com/2dCNdV6.png

as you can see handy notes ( + the DF addon ) uses MULTIPLE times CPU of my entire UI + all other addons together.

this gets worse in raids for some reason the screen shot was during superbloom 

as comparision this is after Superbloom with Reset stats ( no reload )  in a group of 2 players
https://i.imgur.com/ttv9jKD.png

So something is off with handy notes the bigger the group is.

During time Rift
https://i.imgur.com/mtu8jhK.jpg

time rift endboss
https://i.imgur.com/37MMtFk.png

**Comment by Kodiologist** [comment]
I think you may've posted this in the wrong place. This repository is about an Android widget, not a World of Warcraft mod.

**Comment by Evonos** [comment]
> I think you may've posted this in the wrong place. This repository is about an Android widget, not a World of Warcraft mod.

Hey , this might be a glitch on githubs end. , I posted this back then 100% on the addon page of the wow addon , as you see it was back then from 2023 you might have 100% seen this 100% earlier than end of 24 otherwise.
