### ISSUE TITLE
Grid size for each size is one size larger then intended

### ISSUE THREAD

**Issue by Dreyeth** [atd/HandyNotes#9]
HandyNotes version 1.5.

The 1x1 size'd note widget is showing up as 2x2
the 2x2 is showing up as 3x3, all the sizes
are showing up as the next grid size up,
there is no 1x1 note widget showing up.

Running on a Moto E 4G LTE (XT1527) with CyanogenMOD 12.1.

**Comment by Dreyeth** [comment]
Or maybe I should say the widget says its 1x1 but cyanogenmod says its 2x2.

**Comment by atd** [comment]
Sorry @Dreyeth I have not the time to check this, but I will be happy to merge any pull request that fixes it!

**Comment by Dreyeth** [comment]
Thats fine, just wanted to file it.

I don't have the knowledge to fix it.

**Comment by atd** [comment]
Closes via e332530
